// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package echov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EchoAPIClient is the client API for EchoAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoAPIClient interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
}

type echoAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoAPIClient(cc grpc.ClientConnInterface) EchoAPIClient {
	return &echoAPIClient{cc}
}

func (c *echoAPIClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, "/saiprakash_v.echo.v1.EchoAPI/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoAPIServer is the server API for EchoAPI service.
// All implementations should embed UnimplementedEchoAPIServer
// for forward compatibility
type EchoAPIServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
}

// UnimplementedEchoAPIServer should be embedded to have forward compatible implementations.
type UnimplementedEchoAPIServer struct {
}

func (UnimplementedEchoAPIServer) SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

// UnsafeEchoAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoAPIServer will
// result in compilation errors.
type UnsafeEchoAPIServer interface {
	mustEmbedUnimplementedEchoAPIServer()
}

func RegisterEchoAPIServer(s grpc.ServiceRegistrar, srv EchoAPIServer) {
	s.RegisterService(&EchoAPI_ServiceDesc, srv)
}

func _EchoAPI_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoAPIServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saiprakash_v.echo.v1.EchoAPI/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoAPIServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EchoAPI_ServiceDesc is the grpc.ServiceDesc for EchoAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EchoAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saiprakash_v.echo.v1.EchoAPI",
	HandlerType: (*EchoAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _EchoAPI_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echo/v1/echo.proto",
}
